#############################################################################
# Makefile for building: pcgl
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  pcgl.pro
# Template: app
# Command: /home/loux/Documents/QtInstall/5.4/gcc_64/bin/qmake -o Makefile pcgl.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../Documents/QtInstall/5.4/gcc_64/mkspecs/linux-g++ -I. -I../../Documents/QtInstall/5.4/gcc_64/include -I../../Documents/QtInstall/5.4/gcc_64/include/QtQuick -I../../Documents/QtInstall/5.4/gcc_64/include/QtGui -I../../Documents/QtInstall/5.4/gcc_64/include/QtQml -I../../Documents/QtInstall/5.4/gcc_64/include/QtNetwork -I../../Documents/QtInstall/5.4/gcc_64/include/QtCore -I.
QMAKE         = /home/loux/Documents/QtInstall/5.4/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = pcgl1.0.0
DISTDIR = /home/loux/Bureau/TestQML/.tmp/pcgl1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/loux/Documents/QtInstall/5.4/gcc_64 -Wl,-rpath,/home/loux/Documents/QtInstall/5.4/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/loux/Documents/QtInstall/5.4/gcc_64/lib -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = PointCloud.cpp \
		Ply.cpp \
		main.cpp qrc_pcgl.cpp \
		moc_PointCloud.cpp
OBJECTS       = PointCloud.o \
		Ply.o \
		main.o \
		qrc_pcgl.o \
		moc_PointCloud.o
DIST          = ../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/unix.conf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/linux.conf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/g++-base.conf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/qconfig.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/qt_config.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/spec_post.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/default_pre.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/default_post.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/warn_on.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/qt.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/resources.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/moc.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/exceptions.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/yacc.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/lex.prf \
		pcgl.pro PointCloud.h PointCloud.cpp \
		Ply.cpp \
		main.cpp
QMAKE_TARGET  = pcgl
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = pcgl


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pcgl.pro ../../Documents/QtInstall/5.4/gcc_64/mkspecs/linux-g++/qmake.conf ../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/unix.conf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/linux.conf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/g++-base.conf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/qconfig.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/qt_config.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/spec_post.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/default_pre.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/default_post.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/warn_on.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/qt.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/resources.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/moc.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/exceptions.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/yacc.prf \
		../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/lex.prf \
		pcgl.pro \
		pcgl.qrc \
		/home/loux/Documents/QtInstall/5.4/gcc_64/lib/libQt5Quick.prl \
		/home/loux/Documents/QtInstall/5.4/gcc_64/lib/libQt5Gui.prl \
		/home/loux/Documents/QtInstall/5.4/gcc_64/lib/libQt5Core.prl \
		/home/loux/Documents/QtInstall/5.4/gcc_64/lib/libQt5Qml.prl \
		/home/loux/Documents/QtInstall/5.4/gcc_64/lib/libQt5Network.prl
	$(QMAKE) -o Makefile pcgl.pro
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/spec_pre.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/shell-unix.conf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/unix.conf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/linux.conf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/gcc-base.conf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/g++-base.conf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/common/g++-unix.conf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/qconfig.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/qt_functions.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/qt_config.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/spec_post.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/default_pre.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/resolve_config.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/default_post.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/warn_on.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/qt.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/resources.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/moc.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/unix/opengl.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/unix/thread.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/testcase_targets.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/exceptions.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/yacc.prf:
../../Documents/QtInstall/5.4/gcc_64/mkspecs/features/lex.prf:
pcgl.pro:
pcgl.qrc:
/home/loux/Documents/QtInstall/5.4/gcc_64/lib/libQt5Quick.prl:
/home/loux/Documents/QtInstall/5.4/gcc_64/lib/libQt5Gui.prl:
/home/loux/Documents/QtInstall/5.4/gcc_64/lib/libQt5Core.prl:
/home/loux/Documents/QtInstall/5.4/gcc_64/lib/libQt5Qml.prl:
/home/loux/Documents/QtInstall/5.4/gcc_64/lib/libQt5Network.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile pcgl.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents pcgl.qrc $(DISTDIR)/
	$(COPY_FILE) --parents PointCloud.h $(DISTDIR)/
	$(COPY_FILE) --parents PointCloud.cpp Ply.cpp main.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_pcgl.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_pcgl.cpp
qrc_pcgl.cpp: pcgl.qrc \
		main.qml
	/home/loux/Documents/QtInstall/5.4/gcc_64/bin/rcc -name pcgl pcgl.qrc -o qrc_pcgl.cpp

compiler_moc_header_make_all: moc_PointCloud.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_PointCloud.cpp
moc_PointCloud.cpp: ../../Documents/QtInstall/5.4/gcc_64/include/QtQuick/QQuickItem \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQuick/qquickitem.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQuick/qtquickglobal.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qglobal.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qconfig.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qfeatures.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qtypetraits.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qsysinfo.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qlogging.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qflags.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qmutex.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qnumeric.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqml.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmlprivate.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qtqmlglobal.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qvariant.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qbytearray.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qrefcount.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qnamespace.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qarraydata.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qstring.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qchar.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qlist.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qalgorithms.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qiterator.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qmetatype.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qisenum.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qmap.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qpair.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qdebug.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qhash.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qtextstream.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qiodevice.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qobject.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qcoreevent.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qobject_impl.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qlocale.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qshareddata.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qvector.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qpoint.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qset.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qstringlist.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qdatastream.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qregexp.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qurl.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qurlquery.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmlparserstatus.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmllist.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qmetaobject.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmlcomponent.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmlerror.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qjsvalue.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/QObject \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/QList \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qevent.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qregion.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qrect.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qmargins.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qsize.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qkeysequence.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qfile.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qfiledevice.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qvector2d.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qfont.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qaccessible.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qcoreapplication.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qeventloop.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qcolor.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qrgb.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QOpenGLFunctions \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglfunctions.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopengl.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qt_windows.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopengles2ext.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglext.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglcontext.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/QScopedPointer \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QSurfaceFormat \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qsurfaceformat.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qvector3d.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qvector4d.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qmatrix4x4.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qquaternion.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qgenericmatrix.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QOpenGLBuffer \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglbuffer.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QOpenGLVertexArrayObject \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglvertexarrayobject.h \
		PointCloud.h
	/home/loux/Documents/QtInstall/5.4/gcc_64/bin/moc $(DEFINES) -I/home/loux/Documents/QtInstall/5.4/gcc_64/mkspecs/linux-g++ -I/home/loux/Bureau/TestQML -I/home/loux/Documents/QtInstall/5.4/gcc_64/include -I/home/loux/Documents/QtInstall/5.4/gcc_64/include/QtQuick -I/home/loux/Documents/QtInstall/5.4/gcc_64/include/QtGui -I/home/loux/Documents/QtInstall/5.4/gcc_64/include/QtQml -I/home/loux/Documents/QtInstall/5.4/gcc_64/include/QtNetwork -I/home/loux/Documents/QtInstall/5.4/gcc_64/include/QtCore PointCloud.h -o moc_PointCloud.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

PointCloud.o: PointCloud.cpp PointCloud.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQuick/QQuickItem \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQuick/qquickitem.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQuick/qtquickglobal.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qglobal.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qconfig.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qfeatures.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qtypetraits.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qsysinfo.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qlogging.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qflags.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qmutex.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qnumeric.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqml.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmlprivate.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qtqmlglobal.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qvariant.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qbytearray.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qrefcount.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qnamespace.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qarraydata.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qstring.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qchar.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qlist.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qalgorithms.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qiterator.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qmetatype.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qisenum.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qmap.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qpair.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qdebug.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qhash.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qtextstream.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qiodevice.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qobject.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qcoreevent.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qobject_impl.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qlocale.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qshareddata.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qvector.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qpoint.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qset.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qstringlist.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qdatastream.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qregexp.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qurl.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qurlquery.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmlparserstatus.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmllist.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qmetaobject.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmlcomponent.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmlerror.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qjsvalue.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/QObject \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/QList \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qevent.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qregion.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qrect.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qmargins.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qsize.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qkeysequence.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qfile.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qfiledevice.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qvector2d.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qfont.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qaccessible.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qcoreapplication.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qeventloop.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qcolor.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qrgb.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QOpenGLFunctions \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglfunctions.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopengl.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qt_windows.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopengles2ext.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglext.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglcontext.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/QScopedPointer \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QSurfaceFormat \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qsurfaceformat.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qvector3d.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qvector4d.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qmatrix4x4.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qquaternion.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qgenericmatrix.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QOpenGLBuffer \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglbuffer.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QOpenGLVertexArrayObject \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglvertexarrayobject.h \
		Ply.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQuick/qquickwindow.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qwindow.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/QEvent \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/QMargins \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/QRect \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qsurface.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qicon.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qpixmap.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qimage.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qtransform.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qmatrix.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qpolygon.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qline.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qpainterpath.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qpixelformat.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qcursor.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QOpenGLContext
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PointCloud.o PointCloud.cpp

Ply.o: Ply.cpp Ply.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Ply.o Ply.cpp

main.o: main.cpp ../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QGuiApplication \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qguiapplication.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qcoreapplication.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qglobal.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qconfig.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qfeatures.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qtypetraits.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qsysinfo.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qlogging.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qflags.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qmutex.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qnumeric.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qstring.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qchar.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qbytearray.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qrefcount.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qnamespace.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qarraydata.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qobject.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qlist.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qalgorithms.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qiterator.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qcoreevent.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qmetatype.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qisenum.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qobject_impl.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qeventloop.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qinputmethod.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qlocale.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qvariant.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qmap.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qpair.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qdebug.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qhash.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qtextstream.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qiodevice.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qvector.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qpoint.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qset.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qstringlist.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qdatastream.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qregexp.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qshareddata.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qsize.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQuick/QQuickView \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQuick/qquickview.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQuick/qquickwindow.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQuick/qtquickglobal.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopengl.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qt_windows.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopengles2ext.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglext.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qwindow.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/QObject \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/QEvent \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/QMargins \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qmargins.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/QRect \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qrect.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qsurface.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qsurfaceformat.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qicon.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qpixmap.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qcolor.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qrgb.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qimage.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qtransform.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qmatrix.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qpolygon.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qregion.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qline.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qpainterpath.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qpixelformat.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qcursor.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qevent.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qkeysequence.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qurl.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qurlquery.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qfile.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qfiledevice.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qvector2d.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqml.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmlprivate.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qtqmlglobal.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmlparserstatus.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmllist.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/qmetaobject.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmldebug.h \
		PointCloud.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQuick/QQuickItem \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQuick/qquickitem.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmlcomponent.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qqmlerror.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtQml/qjsvalue.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/QList \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qfont.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qaccessible.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QOpenGLFunctions \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglfunctions.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglcontext.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtCore/QScopedPointer \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QSurfaceFormat \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qvector3d.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qvector4d.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qmatrix4x4.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qquaternion.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qgenericmatrix.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QOpenGLBuffer \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglbuffer.h \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/QOpenGLVertexArrayObject \
		../../Documents/QtInstall/5.4/gcc_64/include/QtGui/qopenglvertexarrayobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_pcgl.o: qrc_pcgl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_pcgl.o qrc_pcgl.cpp

moc_PointCloud.o: moc_PointCloud.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PointCloud.o moc_PointCloud.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/loux/Bureau/TestQML/pcgl || mkdir -p $(INSTALL_ROOT)/home/loux/Bureau/TestQML/pcgl
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/home/loux/Bureau/TestQML/pcgl/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/home/loux/Bureau/TestQML/pcgl/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/home/loux/Bureau/TestQML/pcgl/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/home/loux/Bureau/TestQML/pcgl/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

